Fix KeyFrame reference in Parser.php
Some CSS files require the use of the keyFrame class. 

This has been misspelt in the Parser.php class on line 8 and results in the following fatal PHP error:

Fatal error: Class 'Sabberworm\CSS\CSSList\Keyframe' not found in /vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php on line 116